replicacount: 1
containers:
  containerPort: 5000
  image: file-upload
  tag: v1

ports:
  port: 80
  targetPort: 5000
  protocol: TCP

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 256Mi

