apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels: 
      {{- include "file-upload.labels" . | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- include "file-upload.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: file-upload
        image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        -  containerPort: {{ .Values.containers.containerPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

        volumeMounts:
          - name: app-storage
            mountPath: {{ .Values.persistence.mountPath }}
      
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
