apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{ include "file-upload.labels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  #clusterIP: enabled
  ports:
  -  protocol: {{ .Values.ports.protocol }}
     targetPort: {{ .Values.ports.targetPort }}
     port: {{ .Values.ports.port }}