name: Build and Push Image
on:
  push:
    branches:
      - main
jobs:
  build:
    if: github.actor != 'github-action[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    #CHECKOUT CODE
      - name: Checkout Code
        uses: actions/checkout@v4
    #GHCR LOGIN
      - name: Login to GHCR 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io 
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
    #BUILD IMAGE
      - name: Build Image
        run: |
          docker build -t ghcr.io/devops0959-pixel/file-upload-app:${{ github.sha }} .

    #PUSH IMAGE
      - name: Push Image
        run: |
          docker push ghcr.io/devops0959-pixel/file-upload-app:${{ github.sha }}

    #UPDATE IMAGE TAG
      - name: Update values.yaml
        run: | 
          yq -i '.containers.tag = env(GITHUB_SHA)' values.yaml

    #CONFIGURE  GIT
      - name: Configure GIT
        run: | 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

    #COMMIT AND PUSH
      - name: Commit and Push 
        run: |
          git add values.yaml
          git commit -m "Update image tag to ${{ github.sha }} [skip ci]" || echo "No changes to commit"
          git push 
